os: linux
language: scala
sudo: required
dist: trusty
scala:
  - 2.11.12
jdk:
  - oraclejdk8
before_script:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
script:
  - sbt clean test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.cache/coursier/v1
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
